/* DO NOT EDIT THIS FILE - it is machine generated */
/// @file Wn_FacePortrait.h
/// @brief
/// @details
/// @author		chenghuaiyu@sina.com
/// @date		2014-10-5
/// @version	A001
/// @par Copyright (c):
///        Science And Technology Co.,Ltd.
/// @par History:
///		version: author, date, desc\n

#ifndef __WN_FACE_PORTRAIT_H__
#define __WN_FACE_PORTRAIT_H__

#include <jni.h>
#include <Wn_FacePortrait.h>
#include <com_example_testopencv_ImageProc.h>


typedef enum Wn_Error_T
{
	WN_ERROR_NONE,
	WN_ERROR_PARAMETER,
	WN_ERROR_FAIL,


}
Wn_Error;

#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT jint JNICALL Java_com_example_testopencv_ImageProc_DecorateFace
  (JNIEnv *env, jobject jclass, jobject newMat, jobject srcMat)
{
	jint bint =(jint) DecorateFace(newMat, srcMat);

	return bint;
}




#ifdef __cplusplus
} // extern "C"
#endif


#endif


