/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testopencv_ImageProc */

#ifndef _Included_com_example_testopencv_ImageProc
#define _Included_com_example_testopencv_ImageProc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testopencv_ImageProc
 * Method:    DecorateFace
 * Signature: (Lorg/opencv/core/Mat;Lorg/opencv/core/Mat;)I
 */
JNIEXPORT jint JNICALL Java_com_example_testopencv_ImageProc_DecorateFace
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
